# Use Node.js base image
FROM node:22.17.1-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy rest of the server files
COPY . .

# Expose port
EXPOSE 5050

# Start the server
CMD ["npm", "start"]
